import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiOutlineCloudDownload,
  AiOutlineGlobal,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/Mitch.png";
import code from "../public/Dassault.png";
import design from "../public/coghlin-companies-web-logo-22.png";
import consulting from "../public/Dassault.png";
import Image from "next/image";
import web1 from "../public/sapience.png";
import web2 from "../public/experimentmusic.png";
import web3 from "../public/triply.png";
import web4 from "../public/googleanalytics.png";
import Typewriter from 'typewriter-effect';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Miitch's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <div class="text-2xl flex justify-center gap-2">
          <a href="https://www.youtube.com/channel/UCNtjzKme85NQ4xfAZWK3wLw" target="_blank" rel="noopener noreferrer" class = "hover:text-teal-400 py-1">
              <AiOutlineGlobal /> </a>
            <h1 className="uppercase">Boston, MA</h1>
            </div>
            <ul className="flex items-center">
            
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className= "cursor-pointer text-2xl"
                />
        
              </ul>
            
          </nav>
          <div className="text-center p=10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Mitch Mondro
            </h2>
            
            <div class="text-3xl flex justify-center gap-2 p-6">
            <a  href="Mitch_Mondro_Resume.pdf" target="_blank" rel="noopener noreferrer" class="
            rounded 
            inline-block 
            px-12 
            py-3 
            bg-gradient-to-r from-cyan-500 text- to-teal-500 
            text-white 
            font-sans 
            text-lg 
            leading-tight 
            shadow-md 
            hover:bg-blue-700 
            hover:shadow-lg 
            focus:bg-blue-700 
            focus:shadow-lg 
            focus:outline-none 
            focus:ring-0 
            active:bg-blue-800 
            active:shadow-lg 
            transition 
            duration-150 
            ease-in-out">
                  Resume
            </a>
            <a href="Mitch_Mondro_Resume.pdf" download="download resume" target="_blank" rel="noopener noreferrer" class = "py-2 flex justify-center gap-4 text-black dark:text-white hover:text-teal-400">
              <AiOutlineCloudDownload /> </a>
            </div>

            
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>

            <div class="p-6 text-5xl flex justify-center gap-8 text-black dark:text-white">
              
              <a href="https://twitter.com/mitchellmondro" target="_blank" rel="noopener noreferrer" class = "hover:text-teal-400">
              <AiFillTwitterCircle /> </a>
              <a href="https://www.linkedin.com/in/mitchellmondro/" target="_blank" rel="noopener noreferrer" class = "hover:text-teal-400">
              <AiFillLinkedin /> </a>
              <a href="https://www.youtube.com/channel/UCNtjzKme85NQ4xfAZWK3wLw" target="_blank" rel="noopener noreferrer" class = "hover:text-teal-400">
              <AiFillYoutube /> </a>
            
            </div>
          </div>
        </section>
        <section>

          <div className="flex justify-center">
            <h3 className="text-3xl dark:text-white ">Featured Projects</h3>
            
          </div>

        
          <div className="lg:flex flex-wrap gap-10 flex">
            <div className=" shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 w-1/2">
              <Image src={web1} className="border-2 border-grey rounded-xl w-full" width={400} height={300} />
              <h2 className="text-xl font-medium pt-8 pb-2">
              Clark Ureka Challenge: Sapeince News  
              </h2>
              <p> 
              Won $500 in funding in a Shark Tank like competition at Clark where my team and I built and pitched a web application that used machine learning to predict bias and factualness likeliness in online news articles. The web app took the input of a news article URL and delivered a bias factualness prediction of that article from extreme left to extreme right. The algorithm was trained on thousands of publications that were labeled for political bias and factualness using the International Fact Checking Network.
              </p>
            </div>
          
            <div className=" shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 w-1/2">
              <Image src={web2} className="border-2 border-grey rounded-xl w-full" width={400} height={300} />
              <h2 className="text-xl font-medium pt-8 pb-2">
              YouTube Channel 
              </h2>
              <p> 
              Built an audience of 6,500 subscribers on my instrumental YouTube channel. Utilized SEO and content creation techniques to attract new subscribers and generate viral videos.
              </p>
            </div>
            </div>

            <div>
            <div className=" shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={web4} className="border-2 border-grey rounded-xl" width={400} height={300} />
              <h2 className="text-xl font-medium pt-8 pb-2">
              Website Development Agency: Dapper Bros
              </h2>
              <p className="py-2">
                Freelance design and web development company I started with my brother to help non technical businesses launch a fully functional website that is easy to update and maintain. We have developed an iterative process to build high quality websites that leave a strong first impression and build trust.
              </p>
              <h4 className="py-4 text-teal-600">We handle:</h4>
              <p className="text-gray-800 py-1">🎨 Design</p>
              <p className="text-gray-800 py-1">✍️ Copy</p>
              <p className="text-gray-800 py-1">🛠️ Development</p>
              <p className="text-gray-800 py-1">🚀 Deployment</p>
            </div>
          </div>
        </section>



        <section className="py-10">
          
          <div>
            
      
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
<h2 className="py-5 text-xl dark:text-white"> Triply Facebook and Instagram Ad Campaign</h2>
<p className=" flex justify-center dark:text-white" > 
Tested viability of new travel application for client by building a landing page and generating traffic via Facebook/ Instagram ad campaign. Captured email list of potential users for application launch. 
            </p>
            </div>

            <div>
            <h3 className="text-x py-2 dark:text-white md:text-4xl">
              Skills <Typewriter class="text-sm" options ={{
                strings: [
                  "Programming Languages/Frameworks:  Javascript ES6, Python, HTML, CSS, SQL, Tailwind, Solidity, React, Next.js, Flask",
                  "Analytics Applications: Google Analytics, Google Ad Words, Optimizely, SEMrush, HubSpot",
                  "Design Applications: Adobe: Illustrator, Photoshop, Premiere, Figma, Wordpress, Webflow, Canva, Midjourney",
                  "Interests: Baseball, Golf, Music Production, Travel, NFTs, Crypto, Writing, Powerlifting"
                ],
                autoStart: true,
                loop: true,
                delay: 30
              }}
              />
            </h3>
            </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}
